<?php defined('SYSTEMPATH') || exit('No direct script access allowed'); ?>

CRITICAL - 2022-04-18 09:18:29 --> Access denied for user '****'@'localhost' (using password: YES)
#0 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(376): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseBuilder.php(1476): CodeIgniter\Database\BaseConnection->query('SELECT `passwor...', Array, false)
#3 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Model\Auth.php(112): CodeIgniter\Database\BaseBuilder->get()
#4 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Core\Controllers\Admin\Login.php(54): Soulcms\Model\Auth->login('admin', '123456')
#5 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(838): Soulcms\Controllers\Admin\Login->index()
#6 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(335): CodeIgniter\CodeIgniter->runController(Object(Soulcms\Controllers\Admin\Login))
#7 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(245): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Init.php(310): CodeIgniter\CodeIgniter->run()
#9 D:\phpstudy_pro\WWW\cn.test.com\index.php(47): require('D:\\phpstudy_pro...')
#10 D:\phpstudy_pro\WWW\cn.test.com\admin.php(9): require('D:\\phpstudy_pro...')
#11 {main}
CRITICAL - 2022-04-18 09:18:35 --> Access denied for user '****'@'localhost' (using password: YES)
#0 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(376): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseBuilder.php(1476): CodeIgniter\Database\BaseConnection->query('SELECT `passwor...', Array, false)
#3 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Model\Auth.php(112): CodeIgniter\Database\BaseBuilder->get()
#4 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Core\Controllers\Admin\Login.php(54): Soulcms\Model\Auth->login('admin', '123456')
#5 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(838): Soulcms\Controllers\Admin\Login->index()
#6 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(335): CodeIgniter\CodeIgniter->runController(Object(Soulcms\Controllers\Admin\Login))
#7 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(245): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Init.php(310): CodeIgniter\CodeIgniter->run()
#9 D:\phpstudy_pro\WWW\cn.test.com\index.php(47): require('D:\\phpstudy_pro...')
#10 D:\phpstudy_pro\WWW\cn.test.com\admin.php(9): require('D:\\phpstudy_pro...')
#11 {main}
CRITICAL - 2022-04-18 09:19:27 --> Access denied for user '****'@'localhost' (using password: YES)
#0 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(376): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseBuilder.php(1476): CodeIgniter\Database\BaseConnection->query('SELECT `passwor...', Array, false)
#3 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Model\Auth.php(112): CodeIgniter\Database\BaseBuilder->get()
#4 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Core\Controllers\Admin\Login.php(54): Soulcms\Model\Auth->login('admin', '123456')
#5 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(838): Soulcms\Controllers\Admin\Login->index()
#6 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(335): CodeIgniter\CodeIgniter->runController(Object(Soulcms\Controllers\Admin\Login))
#7 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(245): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Init.php(310): CodeIgniter\CodeIgniter->run()
#9 D:\phpstudy_pro\WWW\cn.test.com\index.php(47): require('D:\\phpstudy_pro...')
#10 D:\phpstudy_pro\WWW\cn.test.com\admin.php(9): require('D:\\phpstudy_pro...')
#11 {main}
CRITICAL - 2022-04-18 09:20:30 --> Access denied for user '****'@'localhost' (using password: YES)
#0 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(376): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseBuilder.php(1476): CodeIgniter\Database\BaseConnection->query('SELECT `passwor...', Array, false)
#3 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Model\Auth.php(112): CodeIgniter\Database\BaseBuilder->get()
#4 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Core\Controllers\Admin\Login.php(54): Soulcms\Model\Auth->login('admin', '123456')
#5 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(838): Soulcms\Controllers\Admin\Login->index()
#6 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(335): CodeIgniter\CodeIgniter->runController(Object(Soulcms\Controllers\Admin\Login))
#7 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(245): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Init.php(310): CodeIgniter\CodeIgniter->run()
#9 D:\phpstudy_pro\WWW\cn.test.com\index.php(47): require('D:\\phpstudy_pro...')
#10 D:\phpstudy_pro\WWW\cn.test.com\admin.php(9): require('D:\\phpstudy_pro...')
#11 {main}
CRITICAL - 2022-04-18 09:20:32 --> Access denied for user '****'@'localhost' (using password: YES)
#0 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(376): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseBuilder.php(1476): CodeIgniter\Database\BaseConnection->query('SELECT `passwor...', Array, false)
#3 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Model\Auth.php(112): CodeIgniter\Database\BaseBuilder->get()
#4 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Core\Controllers\Admin\Login.php(54): Soulcms\Model\Auth->login('admin', '123456')
#5 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(838): Soulcms\Controllers\Admin\Login->index()
#6 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(335): CodeIgniter\CodeIgniter->runController(Object(Soulcms\Controllers\Admin\Login))
#7 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(245): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Init.php(310): CodeIgniter\CodeIgniter->run()
#9 D:\phpstudy_pro\WWW\cn.test.com\index.php(47): require('D:\\phpstudy_pro...')
#10 D:\phpstudy_pro\WWW\cn.test.com\admin.php(9): require('D:\\phpstudy_pro...')
#11 {main}
CRITICAL - 2022-04-18 09:21:23 --> Access denied for user '****'@'localhost' (using password: YES)
#0 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(376): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseBuilder.php(1476): CodeIgniter\Database\BaseConnection->query('SELECT `passwor...', Array, false)
#3 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Model\Auth.php(112): CodeIgniter\Database\BaseBuilder->get()
#4 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Core\Controllers\Admin\Login.php(54): Soulcms\Model\Auth->login('admin', '123456')
#5 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(838): Soulcms\Controllers\Admin\Login->index()
#6 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(335): CodeIgniter\CodeIgniter->runController(Object(Soulcms\Controllers\Admin\Login))
#7 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(245): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Init.php(310): CodeIgniter\CodeIgniter->run()
#9 D:\phpstudy_pro\WWW\cn.test.com\index.php(47): require('D:\\phpstudy_pro...')
#10 D:\phpstudy_pro\WWW\cn.test.com\admin.php(9): require('D:\\phpstudy_pro...')
#11 {main}
CRITICAL - 2022-04-18 09:21:27 --> Access denied for user '****'@'localhost' (using password: YES)
#0 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(376): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseBuilder.php(1476): CodeIgniter\Database\BaseConnection->query('SELECT `passwor...', Array, false)
#3 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Model\Auth.php(112): CodeIgniter\Database\BaseBuilder->get()
#4 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Core\Controllers\Admin\Login.php(54): Soulcms\Model\Auth->login('admin', '123456')
#5 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(838): Soulcms\Controllers\Admin\Login->index()
#6 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(335): CodeIgniter\CodeIgniter->runController(Object(Soulcms\Controllers\Admin\Login))
#7 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(245): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Init.php(310): CodeIgniter\CodeIgniter->run()
#9 D:\phpstudy_pro\WWW\cn.test.com\index.php(47): require('D:\\phpstudy_pro...')
#10 D:\phpstudy_pro\WWW\cn.test.com\admin.php(9): require('D:\\phpstudy_pro...')
#11 {main}
CRITICAL - 2022-04-18 09:22:56 --> Access denied for user '****'@'localhost' (using password: YES)
#0 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(376): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseBuilder.php(1476): CodeIgniter\Database\BaseConnection->query('SELECT `passwor...', Array, false)
#3 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Model\Auth.php(112): CodeIgniter\Database\BaseBuilder->get()
#4 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Core\Controllers\Admin\Login.php(54): Soulcms\Model\Auth->login('admin', '123456')
#5 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(838): Soulcms\Controllers\Admin\Login->index()
#6 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(335): CodeIgniter\CodeIgniter->runController(Object(Soulcms\Controllers\Admin\Login))
#7 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(245): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Init.php(310): CodeIgniter\CodeIgniter->run()
#9 D:\phpstudy_pro\WWW\cn.test.com\index.php(47): require('D:\\phpstudy_pro...')
#10 D:\phpstudy_pro\WWW\cn.test.com\admin.php(9): require('D:\\phpstudy_pro...')
#11 {main}
CRITICAL - 2022-04-18 09:23:34 --> Access denied for user '****'@'localhost' (using password: YES)
#0 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(376): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseBuilder.php(1476): CodeIgniter\Database\BaseConnection->query('SELECT `passwor...', Array, false)
#3 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Model\Auth.php(112): CodeIgniter\Database\BaseBuilder->get()
#4 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Core\Controllers\Admin\Login.php(54): Soulcms\Model\Auth->login('admin', '123456')
#5 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(838): Soulcms\Controllers\Admin\Login->index()
#6 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(335): CodeIgniter\CodeIgniter->runController(Object(Soulcms\Controllers\Admin\Login))
#7 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(245): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Init.php(310): CodeIgniter\CodeIgniter->run()
#9 D:\phpstudy_pro\WWW\cn.test.com\index.php(47): require('D:\\phpstudy_pro...')
#10 D:\phpstudy_pro\WWW\cn.test.com\admin.php(9): require('D:\\phpstudy_pro...')
#11 {main}
CRITICAL - 2022-04-18 09:24:09 --> Access denied for user '****'@'localhost' (using password: YES)
#0 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(376): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Core\View.php(1843): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `...')
#3 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Core\View.php(1799): Soulcms\View->_query('SELECT * FROM `...', '', 0)
#4 D:\phpstudy_pro\WWW\cn.test.com\cache_cn\template\template_pc_default_home_index.html.cache.php(117): Soulcms\View->list_tag('action=module m...')
#5 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Core\View.php(206): include('D:\\phpstudy_pro...')
#6 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Core\Controllers\Home.php(37): Soulcms\View->display('index.html')
#7 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Core\Controllers\Home.php(81): Soulcms\Controllers\Home->_index()
#8 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(838): Soulcms\Controllers\Home->index()
#9 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(335): CodeIgniter\CodeIgniter->runController(Object(Soulcms\Controllers\Home))
#10 D:\phpstudy_pro\WWW\cn.test.com\mysoul\System\CodeIgniter.php(245): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\phpstudy_pro\WWW\cn.test.com\mysoul\Fcms\Init.php(310): CodeIgniter\CodeIgniter->run()
#12 D:\phpstudy_pro\WWW\cn.test.com\index.php(47): require('D:\\phpstudy_pro...')
#13 {main}
